export enum SERVICES {
  'housing' = 'housing',
  'clothes' = 'clothes',
  'food' = 'food',
  'aid' = 'aid',
}

export const SERVICES_LABELS = new Map([
  [SERVICES.housing, 'Житло'],
  [SERVICES.clothes, 'Одяг'],
  [SERVICES.food, 'Їжа'],
  [SERVICES.aid, 'Медична допомога'],
]);

export const ORGANIZATION_FORM_VALIDATION = {
  title: (value) => (value.length === 0 ? 'Must not be empty.' : null),
  phoneNumber: (value) => (value.length === 0 ? 'Must not be empty.' : null),
};

export const CENTER_DATA_FORM_VALIDATION = {
  title: (value) => (value.length === 0 ? 'Must not be empty.' : null),
  address: (value) => (value.length === 0 ? 'Must not be empty.' : null),
  phoneNumber: (value) => (value.length === 0 ? 'Must not be empty.' : null),
  start: (value) => (value.length === 0 ? 'Must not be empty.' : null),
  end: (value) => (value.length === 0 ? 'Must not be empty.' : null),
  longitude: (value) => (value.length === 0 ? 'Must not be empty.' : null),
  latitude: (value) => (value.length === 0 ? 'Must not be empty.' : null),
  service: (value) => (value.length === 0 ? 'Must not be empty.' : null),
};

export const MOCK_ORGANIZATIONS = [
  {
    id: '1',
    title: 'Повернись ситим',
    photoUrl: '/images/mock.png',
    phoneNumber: '121',
    centers: [
      {
        id: '11',
        title: 'ГВЦ - Deribon Food',
        phoneNumber: '121',
        start: '9:00',
        end: '18:00',
        longitude: '',
        latitude: '',
        city: 'місто А',
        address: 'вул. Дерибасівська, 2г.',
        service: 'food',
      },
      {
        id: '12',
        title: 'ГВЦ - Deribon Food',
        phoneNumber: '121',
        start: '9:00',
        end: '18:00',
        longitude: '',
        latitude: '',
        city: 'місто А',
        address: 'вул. Дерибасівська, 2г.',
        service: 'food',
      },
      {
        id: '13',
        title: 'ГВЦ - Deribon Food',
        phoneNumber: '121',
        start: '9:00',
        end: '18:00',
        longitude: '',
        latitude: '',
        city: 'місто А',
        address: 'вул. Дерибасівська, 2г.',
        service: 'food',
      },
    ],
  },
  {
    id: '2',
    title: 'Повернись ситим',
    photoUrl: '/images/mock.png',
    centers: [
      {
        id: '21',
        title: 'ГВЦ - Deribon Food',
        phoneNumber: '121',
        start: '9:00',
        end: '18:00',
        longitude: '',
        latitude: '',
        city: 'місто А',
        address: 'вул. Дерибасівська, 2г.',
        service: 'food',
      },
      {
        id: '22',
        title: 'ГВЦ - Deribon Food',
        phoneNumber: '121',
        start: '9:00',
        end: '18:00',
        longitude: '',
        latitude: '',
        city: 'місто А',
        address: 'вул. Дерибасівська, 2г.',
        service: 'food',
      },
      {
        id: '23',
        title: 'ГВЦ - Deribon Food',
        phoneNumber: '121',
        start: '9:00',
        end: '18:00',
        longitude: '',
        latitude: '',
        city: 'місто А',
        address: 'вул. Дерибасівська, 2г.',
        service: 'food',
      },
    ],
  },
  {
    id: '3',
    title: 'Повернись ситим',
    photoUrl: '/images/mock.png',
    centers: [
      {
        id: '31',
        title: 'ГВЦ - Deribon Food',
        phoneNumber: '121',
        start: '9:00',
        end: '18:00',
        longitude: '',
        latitude: '',
        city: 'місто А',
        address: 'вул. Дерибасівська, 2г.',
        service: 'food',
      },
      {
        id: '32',
        title: 'ГВЦ - Deribon Food',
        phoneNumber: '121',
        start: '9:00',
        end: '18:00',
        longitude: '',
        latitude: '',
        city: 'місто А',
        address: 'вул. Дерибасівська, 2г.',
        service: 'food',
      },
      {
        id: '33',
        title: 'ГВЦ - Deribon Food',
        phoneNumber: '121',
        start: '9:00',
        end: '18:00',
        longitude: '',
        latitude: '',
        city: 'місто А',
        address: 'вул. Дерибасівська, 2г.',
        service: 'food',
      },
    ],
  },
];
